### ISSUE TITLE
Export Benchmark Results

### ISSUE THREAD

**Issue by RaduTerec** [atmoos/GlassView#1]
Export the benchmark results from a project to a predefined location.

Tasks:
- [ ] write an exporter which receives an assembly as parameter and finds the corresponding benchmark results.
- [ ] configure exporter output format via appsettings: graphs, html, json, txt
- [ ] configure the output location via appsettings

**Comment by atmoos** [comment]
Also, I'll update the design documents with architecture decisions taken while implementing this story.
